import type { NextPage } from 'next';
import Head from 'next/head';
import { Box, Grid, Image, Title, Text, Anchor } from '@mantine/core';
import { useState } from 'react';
import { Controller, EffectFade, Navigation as SwiperNavigation } from 'swiper';
import { Swiper, SwiperSlide } from 'swiper/react';
import type { Swiper as SwiperClass } from 'swiper/types';
import SlideNextButton from '../components/SlideNextButton';
import SlidePreviousButton from '../components/SlidePreviousButton';
import Navigation from '../components/Navigation';
import 'swiper/css';
import 'swiper/css/effect-fade';

const ShopNowLink = () => (
  <Anchor
    href=""
    sx={theme => ({
      textTransform: 'uppercase',
      letterSpacing: '1ch',
      fontWeight: 600,
      color: theme.colors.brand[0],
      display: 'inline-block',
      '&:hover': {
        textDecoration: 'none',
        color: theme.colors.brand[2],
        img: { fill: theme.colors.brand[2] },
        svg: { fill: theme.colors.brand[2] }
      }
    })}
  >
    Shop Now
    <Box
      component="svg"
      width="40"
      height="12"
      xmlns="http://www.w3.org/2000/svg"
      sx={{ display: 'inline-block', marginLeft: 32 }}
    >
      <path
        d="M34.05 0l5.481 5.527h.008v.008L40 6l-.461.465v.063l-.062-.001L34.049 12l-.662-.668 4.765-4.805H0v-1h38.206l-4.82-4.86L34.05 0z"
        fillRule="nonzero"
      />
    </Box>
  </Anchor>
);

const slideContent = [
  {
    title: 'Discover innovate ways to decorate',
    copy: `We provide unmatched quality, comfort, and style for property
      owners across the country. Our experts combine form and
      function in bringing your vision to life. Create a room in
      your own style with our collection and make your property a
      reflection of you and what you love.`,
    image: '/desktop-image-hero-1.jpg',
    alt: 'Modern table furniture'
  },
  {
    title: 'We are available across the globe',
    copy: `With stores all over the world it's easy for you to find
      furniture for your home or place of business. Locally, we're in most
      major cities throughout the country. Find the branch nearest you using
      our store locator. Any questions? Don't hesitate to contact us today.`,
    image: '/desktop-image-hero-2.jpg',
    alt: 'Contemporary office chairs'
  },
  {
    title: 'Manufactured with the best materials',
    copy: `Our modern furniture store provide a high level of quality.
      Our company has invested in advanced technology to ensure that
      every product is made as perfect and as consistent as
      possible. With three decades of experience in this industry,
      we understand what customers want for their home and office.`,
    image: '/desktop-image-hero-3.jpg',
    alt: 'Black folding chair'
  }
] as const;

const Home: NextPage = () => {
  const [controllerSwiper, setControlledSwiper] = useState<SwiperClass>();

  return (
    <>
      <Head>
        <title>Room</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>
      <Grid
        columns={80}
        gutter={0}
        sx={{ maxHeight: '100vh', position: 'relative' }}
      >
        <Grid.Col span={49} sx={{ padding: 0 }}>
          <Box
            component={Swiper}
            modules={[EffectFade]}
            onSwiper={setControlledSwiper}
            effect="fade"
            allowTouchMove={false}
          >
            <Navigation />
            {slideContent.map(({ image, alt }) => (
              <SwiperSlide key={alt}>
                <Image src={image} alt={alt} />
              </SwiperSlide>
            ))}
          </Box>
        </Grid.Col>
        <Grid.Col
          span={31}
          sx={{
            padding: 0
          }}
        >
          <Box
            component={Swiper}
            modules={[Controller, EffectFade, SwiperNavigation]}
            controller={{ control: controllerSwiper }}
            effect="fade"
            allowTouchMove={false}
            sx={{ height: '100%', position: 'relative' }}
          >
            {slideContent.map(({ title, copy }) => (
              <SwiperSlide key={title}>
                <Box
                  sx={theme => ({
                    padding: 128,
                    backgroundColor: theme.colors.brand[3]
                  })}
                >
                  <Title sx={{ fontSize: 48, lineHeight: 1, fontWeight: 500 }}>
                    {title}
                  </Title>
                  <Text
                    sx={theme => ({
                      fontSize: 14,
                      color: theme.colors.brand[2],
                      marginBlock: 48
                    })}
                  >
                    {copy}
                  </Text>
                  <ShopNowLink />
                </Box>
              </SwiperSlide>
            ))}
            <Box sx={{ position: 'absolute', bottom: 0, left: 0, zIndex: 1 }}>
              <SlidePreviousButton />
              <SlideNextButton />
            </Box>
          </Box>
        </Grid.Col>
        <Grid.Col span={22} sx={{ padding: 0 }}>
          <Image src="/image-about-dark.jpg" alt="Dark furniture" />
        </Grid.Col>
        <Grid.Col
          span={35}
          sx={{ padding: 64, display: 'grid', placeContent: 'center' }}
        >
          <Title
            sx={{
              fontSize: 20,
              textTransform: 'uppercase',
              letterSpacing: '0.25em',
              marginBlock: '0.75em',
              fontWeight: '700'
            }}
          >
            About our Furniture
          </Title>
          <Text sx={theme => ({ fontSize: 14, color: theme.colors.brand[2] })}>
            Our multifunctional collection blends design and function to suit
            your individual taste. Make each room unique, or pick a cohesive
            theme that best expresses your interests and what inspires you. Find
            the furniture pieces you need, from traditional to cotemporary
            styles or anything in between. Product specialists are available to
            help you create your dream space.
          </Text>
        </Grid.Col>
        <Grid.Col span={23} style={{ padding: 0 }}>
          <Image
            src="/image-about-light.jpg"
            alt="Light colored chair"
            styles={{
              imageWrapper: { height: '100%' },
              image: { height: '100%!important' }
            }}
          />
        </Grid.Col>
      </Grid>
    </>
  );
};

export default Home;
