import type { NextPage } from 'next';
import Head from 'next/head';
import { Title, Box, Image } from '@mantine/core';
import Logo from '../components/Logo';

const Home: NextPage = () => {
  return (
    <Box
      style={{
        paddingInline: 50
      }}
    >
      <Head>
        <title>Canal Street</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Logo />
      <Title order={1} style={{ fontSize: 65, maxWidth: '28ch', marginBlock: 100 }}>
        Canal Street Market is a carefully curated retail market, food hall & community space open year-round at 265 Canal Street. Support Small Business this weekend!
      </Title>
      <Image src="home-hero.jpg" alt="Home hero" style={{ marginInline: -50 }} />
    </Box>
  );
};

export default Home;
